### ISSUE TITLE
Max height/ Min height isn't calculated correctly

### ISSUE THREAD

**Issue by Masy** [NAAVOO/Noisy#7]
I've played a bit with the heights and imported several height maps into WorldPainter, and it seems that the calculations is completely wrong.

With the settings Min. Height = 0 and Max. Height = 128 it seems to generate values between 0 and 50.

with the settings Min. Height = 128 and Max. Height = 255 it seems to generate values between 55 and 255.

So the clamp function is calculating some wrong values i guess.

**Comment by Masy** [comment]
I think i know where the problem is: It calculates wrong because it doubles the height. here is an example of what i mean:

Since the normal noise is between 0 and 1.0, converting it to 0-255 results in smooth slopes, because every height is used. Your clamp function seems to just double some values resulting in some steep cliffs:
https://i.kncw.eu/i/a96tDxG
Most of the time the height increaes by 2 instead of 1.

**Comment by Masy** [comment]
oh, just realized that this problem also occurs when min and max height are at default (0-255).
Result is this weird looking terracing: https://i.kncw.eu/i/dTbuVKf

**Comment by Masy** [comment]
Okay, i tested a bit more, and there seems to be 2 seperate issues with this:
The first problem occurs when converting the grayScale into the RGB code.

I made a debug message where it would print out the greyscale value at every point. The console for example said the value at [77,255] should be 145.
I exported the heightmap as an image, selected the color of the pixel and it was 72, i really don't know why though.

The second problem is, that the noise values seem to "jump", what causes the terracing.
Debugmessage:
[10:58:49] Noise: 0.7235209
[10:58:49] GrayScale: [255] [240] : 223
[10:58:49] Noise: 0.71885186
[10:58:49] GrayScale: [255] [241] : 222
[10:58:49] Noise: 0.7035822
[10:58:49] GrayScale: [255] [242] : 220

So as you can see, it gets converted correctly, and i checked the normalize function aswell, but somehow a 0.01 diffrence between neighbouring points is too much, no idea how to fix it though...

(i guess the values of the discretePoints differenciate too much so there is a too steep slope -> jumping noise values -> jumping rgb values.)

Possible way to fix this could be to add a function where the discrete points' value gets limited by the previous generated value. so for example if the discretePoint[0,0] has the value 0.5 the discretePoint[0,1] has to be between 0.25 and 0.75 or something.
Only problem:
the point [1,0] has to be limited by [0,0], even though the previous point was [0,RESOLUTION], same with [2,0] limited by [1,0] and so on.

**Comment by navopw** [comment]
Thanks, but this project is not being worked on anymore.
